#!/bin/bash

# Admin Dashboard Integration Test Script
# This script tests that admin changes reflect on the user side

echo "=========================================="
echo "Admin Dashboard Integration Test"
echo "=========================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}Server Status:${NC}"
echo "✓ Next.js dev server is running on http://localhost:3000"
echo ""

echo -e "${YELLOW}Test Checklist:${NC}"
echo ""

echo "1. Environment Setup"
echo "   ☐ Check Supabase connection"
echo "   ☐ Verify admin user exists"
echo "   ☐ Confirm real-time is enabled"
echo ""

echo "2. Admin Dashboard Access"
echo "   ☐ Navigate to http://localhost:3000/admin"
echo "   ☐ Verify admin authentication works"
echo "   ☐ Check all admin pages load"
echo ""

echo "3. Products Management Test"
echo "   ☐ Go to http://localhost:3000/admin/products"
echo "   ☐ Click 'Add Product' button"
echo "   ☐ Fill in product details:"
echo "      - Name: Test Product $(date +%s)"
echo "      - Price: 99.99"
echo "      - Category: Select any category"
echo "      - Description: Test product description"
echo "      - Stock: 10"
echo "   ☐ Save the product"
echo "   ☐ Open http://localhost:3000/products in new tab"
echo "   ☐ ${GREEN}VERIFY:${NC} New product appears immediately"
echo ""

echo "4. Product Update Test"
echo "   ☐ Edit the test product"
echo "   ☐ Change name to 'Updated Test Product'"
echo "   ☐ Change price to 149.99"
echo "   ☐ Save changes"
echo "   ☐ Check http://localhost:3000/products"
echo "   ☐ ${GREEN}VERIFY:${NC} Changes appear instantly"
echo ""

echo "5. Product Delete Test"
echo "   ☐ Delete the test product"
echo "   ☐ Confirm deletion"
echo "   ☐ Check http://localhost:3000/products"
echo "   ☐ ${GREEN}VERIFY:${NC} Product disappears immediately"
echo ""

echo "6. Categories Management Test"
echo "   ☐ Go to http://localhost:3000/admin/categories"
echo "   ☐ Click 'Add Category'"
echo "   ☐ Enter category name: Test Category $(date +%s)"
echo "   ☐ Enter description"
echo "   ☐ Save category"
echo "   ☐ Check http://localhost:3000/products"
echo "   ☐ ${GREEN}VERIFY:${NC} Category appears (may need page load)"
echo ""

echo "7. Real-time Subscription Test"
echo "   ☐ Open browser DevTools (F12)"
echo "   ☐ Go to Console tab"
echo "   ☐ Look for these messages:"
echo "      - '[Realtime] Products subscription status: SUBSCRIBED'"
echo "      - '[v0] Supabase client initialized successfully'"
echo "   ☐ Make a change in admin"
echo "   ☐ ${GREEN}VERIFY:${NC} See '[Realtime] Product changed:' message"
echo ""

echo "8. Error Handling Test"
echo "   ☐ Try creating product with empty name"
echo "   ☐ ${GREEN}VERIFY:${NC} See specific error message"
echo "   ☐ Fill all fields and save"
echo "   ☐ ${GREEN}VERIFY:${NC} Success message appears"
echo ""

echo "9. Cache Revalidation Test"
echo "   ☐ Open http://localhost:3000/products in incognito/private window"
echo "   ☐ Add a product from admin dashboard"
echo "   ☐ Refresh the incognito window"
echo "   ☐ ${GREEN}VERIFY:${NC} New product is visible (cache cleared)"
echo ""

echo "10. Multi-Tab Test"
echo "   ☐ Open http://localhost:3000/products in Tab 1"
echo "   ☐ Open http://localhost:3000/admin/products in Tab 2"
echo "   ☐ Add/edit/delete products in Tab 2"
echo "   ☐ Watch Tab 1 (do NOT refresh manually)"
echo "   ☐ ${GREEN}VERIFY:${NC} Tab 1 updates automatically"
echo ""

echo "=========================================="
echo "Quick Test Commands:"
echo "=========================================="
echo ""
echo "Test admin page loads:"
echo "curl -I http://localhost:3000/admin"
echo ""
echo "Test products API:"
echo "curl http://localhost:3000/api/products | jq '.products | length'"
echo ""
echo "Test categories API:"
echo "curl http://localhost:3000/api/admin/categories"
echo ""

echo "=========================================="
echo "Expected Console Messages:"
echo "=========================================="
echo ""
echo "In Browser Console you should see:"
echo "  ✓ [v0] Supabase client initialized successfully"
echo "  ✓ [Realtime] Products subscription status: SUBSCRIBED"
echo "  ✓ [Realtime] Categories subscription status: SUBSCRIBED"
echo ""
echo "When making changes:"
echo "  ✓ [Realtime] Product changed: {eventType: 'INSERT', ...}"
echo "  ✓ [Realtime] Product changed: {eventType: 'UPDATE', ...}"
echo "  ✓ [Realtime] Product changed: {eventType: 'DELETE', ...}"
echo ""

echo "=========================================="
echo "Troubleshooting:"
echo "=========================================="
echo ""
echo "If changes don't reflect immediately:"
echo "  1. Check browser console for errors"
echo "  2. Verify Supabase real-time is enabled:"
echo "     Run: SUPABASE_REALTIME_SETUP.sql"
echo "  3. Check environment variables are set"
echo "  4. Clear browser cache (Ctrl+Shift+R)"
echo "  5. Restart dev server"
echo ""

echo "If admin access is denied:"
echo "  1. Check user has is_admin = true in profiles table"
echo "  2. Log out and log back in"
echo "  3. Check SUPABASE_SERVICE_ROLE_KEY is set"
echo ""

echo "=========================================="
echo "Ready to test!"
echo "=========================================="
echo ""
echo "Open your browser to: http://localhost:3000"
echo ""
